import { uploadImage } from "./lib/cloudinary.server";

/* =========================
   CONSTANTS
========================= */
const BIGMODEL_TEXT_URL =
  "https://open.bigmodel.cn/api/paas/v4/chat/completions";

const HF_IMAGE_URL =
  "https://router.huggingface.co/hf-inference/models/stabilityai/stable-diffusion-xl-base-1.0";

/* =========================
   IMAGE GENERATION (SAFE)
========================= */
async function generateImageWithHF(prompt) {
  const res = await fetch(HF_IMAGE_URL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.HUGGINGFACE_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ inputs: prompt }),
  });

  if (!res.ok) {
    throw new Error(await res.text());
  }

  const buffer = await res.arrayBuffer();
  return Buffer.from(buffer).toString("base64");
}

/* =========================
   MAIN AI FUNCTION
========================= */
export async function generateProductWithAI({
  title,
  tone = "seo",
  pricing = "medium",
}) {
  if (!title?.trim()) {
    throw new Error("Product title is required for AI generation");
  }

  if (!process.env.BIGMODEL_API_KEY) {
    throw new Error("BIGMODEL_API_KEY missing");
  }

  /* =========================
     1️⃣ TEXT GENERATION
  ========================= */

  const prompt = `
Return ONLY valid JSON.
NO markdown.
NO explanations.

STRICT REQUIREMENTS:
- descriptionHtml MUST be valid HTML and at least 2 paragraphs
- tags MUST be an array of 5–7 lowercase ecommerce keywords
- tags must NOT be empty
- variants[0].price MUST be a string number
- imagePrompt MUST be a short visual description

PRICE RANGE RULES:
- low: 9.99–19.99
- medium: 19.99–49.99
- high: 49.99–99.99

JSON FORMAT:
{
  "descriptionHtml": "<p>...</p>",
  "variants": [{ "title": "Default", "price": "29.99" }],
  "tags": ["tag1", "tag2", "tag3", "tag4", "tag5"],
  "seo": { "title": "", "description": "" },
  "imagePrompt": ""
}

Product title: "${title}"
Tone: ${tone}
Pricing: ${pricing}
`;

  const textRes = await fetch(BIGMODEL_TEXT_URL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.BIGMODEL_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "glm-4-flash",
      messages: [{ role: "user", content: prompt }],
      temperature: 0.7,
    }),
  });

  if (!textRes.ok) {
    throw new Error("BigModel text request failed");
  }

  const textData = await textRes.json();

  let raw =
    textData?.choices?.[0]?.message?.content ??
    textData?.data?.content ??
    textData?.output?.text;

  if (!raw) {
    console.error("❌ BigModel response:", textData);
    throw new Error("Empty AI response");
  }

  raw = raw.replace(/```json|```/gi, "").trim();

  let ai;
  try {
    ai = JSON.parse(raw);
  } catch {
    console.error("❌ AI RAW OUTPUT:", raw);
    throw new Error("Invalid AI JSON");
  }

  /* =========================
     PRICE FALLBACK
  ========================= */
  const priceFallback =
    pricing === "low" ? "14.99" : pricing === "high" ? "79.99" : "29.99";

  /* =========================
     IMAGE GENERATION (NON-BLOCKING)
  ========================= */
  let images = [];

  const imagePrompt =
    ai.imagePrompt ||
    `Professional studio product photo of ${title}, white background, ecommerce`;

  try {
    images = await Promise.all(
      Array.from({ length: 2 }).map(async () => {
        const base64 = await generateImageWithHF(imagePrompt);
        return uploadImage(base64);
      }),
    );
  } catch (err) {
    console.warn("⚠️ Image generation failed:", err.message);
  }

  if (!images.length) {
    images = [
      "https://picsum.photos/600/600?random=101",
      "https://picsum.photos/600/600?random=102",
    ];
  }

  /* =========================
     DESCRIPTION NORMALIZATION (CRITICAL)
  ========================= */
  const descriptionHtml =
    typeof ai.descriptionHtml === "string" &&
    ai.descriptionHtml.replace(/<[^>]+>/g, "").trim().length > 20
      ? ai.descriptionHtml
      : `<p><strong>${title}</strong> is a premium product generated by AI.</p>
         <p>Designed for performance, reliability, and everyday use.</p>`;

  /* =========================
     FINAL PRODUCT OBJECT
  ========================= */
  return {
    title,
    descriptionHtml,
    variants:
      ai.variants?.length > 0
        ? ai.variants.map((v) => ({
            title: v.title || "Default",
            price:
              String(v.price).trim() && Number(v.price) > 0
                ? String(v.price)
                : priceFallback,
          }))
        : [{ title: "Default", price: priceFallback }],
    tags: Array.isArray(ai.tags) ? ai.tags : [],
    seo: {
      title: ai.seo?.title || title,
      description:
        ai.seo?.description || `Buy premium ${title} at the best price.`,
    },
    images,
  };
}
